In [9]:
#Tp N°1
#exo1

import numpy as np
import pandas as pd
exp = np.array([["oui", 'oui'], 
              ["oui", 'non'], 
              ["non", 'oui'], 
              ["non", 'non'],
              ["oui", 'oui'], 
              ["oui", 'non'], 
              ["non", 'oui']
              ])
print(exp)
print(exp[:,1])

[['oui' 'oui']
 ['oui' 'non']
 ['non' 'oui']
 ['non' 'non']
 ['oui' 'oui']
 ['oui' 'non']
 ['non' 'oui']]
['oui' 'non' 'oui' 'non' 'oui' 'non' 'oui']


In [3]:
#Q1: Déterminer le tableau de codage disjoonctif complet
#Déterminer le nombre de valeurs uniques dans chaque colonne
#Et créer le montant approprié de {0,1}
new = np.array([])
for j in range(exp.shape[1]):  #iterer les columns
    un = np.unique(exp[:,j])
    code = np.eye(un.shape[0])
 
    for i in range(exp[:,j].shape[0]):
        #print(v[i])
        r=code[exp[:,j][i]==un]
        #print(r)
        if len(new)==0:
            new = r
        else:
            new = np.append(new,r,axis=0)
print(new)

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [4]:
#splitting the array back to 2 columns
a = new[:exp.shape[0]]
b = new[exp.shape[0]:]

#then joining them back together
arr = np.concatenate((a, b), axis=1)
print(arr)

[[0. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]]


In [5]:
df = pd.DataFrame({0: arr[:,0], 1: arr[:,1], 2: arr[:,2], 3: arr[:,3]})
print(df)

     0    1    2    3
0  0.0  1.0  0.0  1.0
1  0.0  1.0  1.0  0.0
2  1.0  0.0  0.0  1.0
3  1.0  0.0  1.0  0.0
4  0.0  1.0  0.0  1.0
5  0.0  1.0  1.0  0.0
6  1.0  0.0  0.0  1.0


In [6]:
print("Tableau de Distance")
dist = np.zeros((exp.shape[0],exp.shape[0]))

for i in range(arr.shape[0]):
    for j in range(arr.shape[0]):
        a = sum(((arr[i,:]==1)&(arr[j,:]==1)))
        b = sum(((arr[i,:]==1)&(arr[j,:]==0)))
        c = sum(((arr[i,:]==0)&(arr[j,:]==1)))
        d = sum(((arr[i,:]==0)&(arr[j,:]==0)))
        mesure = (b+c)/(a+b+c+d)
        dist[i,j] = mesure
print(dist)

Tableau de Distance
[[0.  0.5 0.5 1.  0.  0.5 0.5]
 [0.5 0.  1.  0.5 0.5 0.  1. ]
 [0.5 1.  0.  0.5 0.5 1.  0. ]
 [1.  0.5 0.5 0.  1.  0.5 0.5]
 [0.  0.5 0.5 1.  0.  0.5 0.5]
 [0.5 0.  1.  0.5 0.5 0.  1. ]
 [0.5 1.  0.  0.5 0.5 1.  0. ]]


In [7]:
#Q2: disemilarity mesure
dist = np.zeros((exp.shape[0],exp.shape[0]))

for i in range(df.shape[1]):
    for j in range(df.shape[1]):
        a = sum(((df[i]==1)&(df[j]==1)))
        b = sum(((df[i]==1)&(df[j]==0)))
        c = sum(((df[i]==0)&(df[j]==1)))
        d = sum(((df[i]==0)&(df[j]==0)))
        mesure = (b+c)/(a+b+c+d)
        dist[i,j] = mesure

In [8]:
#Q3: Reduire le tableau de codage
burt = np.zeros((df.shape[1],df.shape[1]))
rd = pd.DataFrame(data=burt)
for i in range(df.shape[1]):
    rd[i][i] = df.sum(axis=0)[i]
for i in range(df.shape[1]):
    for j in range(df.shape[1]):
        rd[i][j] = sum(df[i]*df[j])
print(rd) 


     0    1    2    3
0  3.0  0.0  1.0  2.0
1  0.0  4.0  2.0  2.0
2  1.0  2.0  3.0  0.0
3  2.0  2.0  0.0  4.0
