In [344]:
#EXO4 de Fichier TP2
#applique l'ACP sur la matrice

import numpy as np
import pandas as pd

matrice = np.array([[2, 3],
                    [4, 5],
                    [6, 1]])
a = np.array([[8, 1, 0],
                    [4, 6, 5],
                    [6, 8, 7],
                    [10, 4, 7],
                    [8, 2, 5],
                    [0, 3, 6]])
df = pd.DataFrame(data=matrice)
print("\nNotre Tableau de données (Sachant que les données sont hétérogènes)\n")
display(df)


Notre Tableau de données (Sachant que les données sont hétérogènes)



0  1
0  2  3
1  4  5
2  6  1

In [345]:
print("\nEtape 1: Centrer le tableau: X = X - g avec g = moyenne\n")
df1 = pd.DataFrame()
for i in df:
    df1[i] = df[i] - df[i].mean()
display(df1)


Etape 1: Centrer le tableau: X = X - g avec g = moyenne



0    1
0 -2.0  0.0
1  0.0  2.0
2  2.0 -2.0

In [346]:
print("\nEtape 2: Calculer la matrice variance covariance: V = 1 / N * Xt * X\n")
df_t = df1.transpose()
vaco = (df1.cov())
V = (1 / df.shape[0]) * vaco
display(V)


Etape 2: Calculer la matrice variance covariance: V = 1 / N * Xt * X



0         1
0  1.333333 -0.666667
1 -0.666667  1.333333

In [347]:
print("\nEtape 3: Déterminer la métrique M:\n")
print("Pour les données homogéne:")
m_ho = np.zeros((df.shape[1], df.shape[1]), float)
np.fill_diagonal(m_ho, 1)
I = pd.DataFrame(data=m_ho)
display(I)
print("\nPour les données hétérogènes:")
m_he = np.zeros((df.shape[1], df.shape[1]), float)
np.fill_diagonal(m_he, 1 / V[0][0])
M = pd.DataFrame(data=m_he)
display(M)


Etape 3: Déterminer la métrique M:

Pour les données homogéne:


0    1
0  1.0  0.0
1  0.0  1.0


Pour les données hétérogènes:


0     1
0  0.75  0.00
1  0.00  0.75

In [348]:
print("\nEtape 4: Recherche des axes principaux Uk de la matrice (VM)\n")
print("=> Calculer les valeurs propres Dét(VM - ΛI) = 0")
#x1 = - vaco[0][1] / df.shape[0] #pour 4-3x0
#x2 = (vaco[0][0] - vaco[0][1]) / df.shape[0] #pour 8 - 3x + 4
#c = 0
#print(vaco, "- x\n", I)
matrice = np.array([[2, 3, 0],
                    [4, 5, 0],
                    [6, 1, 0]])
print(matrice)
print(np.linalg.eigvals(matrice))
print("\n=> Trier Les valeurs propres par ordre décroissant: lambda1 > lamba2..")


Etape 4: Recherche des axes principaux Uk de la matrice (VM)

=> Calculer les valeurs propres Dét(VM - ΛI) = 0
[[2 3 0]
 [4 5 0]
 [6 1 0]]
[ 0.          7.27491722 -0.27491722]

=> Trier Les valeurs propres par ordre décroissant: lambda1 > lamba2..


In [349]:
print("\nEtape 5: Calculer la qualité de représentation: Q\n")
q = 0.0
l = [x1, x2]
i = len(l) - 1
while q < 0.8:
    if i == 0 :
        q = (sum(l)) / sum(l)
        print("LA Qualité =", q)
        print("Les axes principaux sont:", l)
    else: 
        q = (sum(l) - l[i])/ sum(l)
    i -= 1


Etape 5: Calculer la qualité de représentation: Q

LA Qualité = 1.0
Les axes principaux sont: [2.0, 0.6666666666666666]


In [350]:
print("\nEtape 6: Calculer les vacteurs propres Uk: \n")
print(V)


Etape 6: Calculer les vacteurs propres Uk: 

          0         1
0  1.333333 -0.666667
1 -0.666667  1.333333
